### ISSUE TITLE
CH EMED MedicationStatement Profile (Medication Card document) - required nonstructured Dosage to strict? (Oliver Egger)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#16]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medicationstatement-card.html

The nonstructured Dosage is required in CH-EMD is required ( dosage:nonstructured, 1..1 CHEMEDDosageNonStructured), however the CDA-CH EMED spec has a 0..1 cardinality for the non structured dosage part.

https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.4.34&effectiveDate=2019-12-11T11:31:52&language=en-US

IPAG provided the following definition: Dosierung o M
Entweder strukturiert oder im Freitext möglich

Should the nonstructured be also 0..1? 

Point came up with Robert from Cerner during Projectathon preparation

Oliver Egger

**Comment by eHealth-Suisse** [comment]
I agree. It 's "either or", so non structured is not supposed to be mandatory -> change to 0..1
