### ISSUE TITLE
Original Representation of examples are not PFD 1/A compliant (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#17]
ch.fhir.ig.ch-emed#0.2.0 /Bundle-1-1-MedicationTreatmentPlan.html

For the provided examples the included "original representations" are just PDF's, and not in PDF 1/a format. The same PDF's are also used for the corresponding CDA-CH-EMED examples.

Quentin brought this up in the google group, see  https://groups.google.com/d/msgid/epd_projectathon/835d55cd-097b-4dbb-b321-2a60f7937b72n%40googlegroups.com.

Oliver Egger, ahdis

**Comment by eHealth-Suisse** [comment]
> change examples
> note: PDF/A-1 and PDF/A-2 are permitted
> other issue with example, also to be taken into account: https://gazelle.ihe.net/jira/browse/TESEH-96

**Comment by oliveregger** [comment]
> > change examples
> > note: PDF/A-1 and PDF/A-2 are permitted
> > other issue with example, also to be taken into account: https://gazelle.ihe.net/jira/browse/TESEH-96

The binary pdf in the example json contains an error. The "Dosis pro Einheit" for the Beloc Zok MedicationStatement states 2.5mg in the .pdf. In the fhir resource it states 50 mg for the Metoprolol in the Beloc Zok MedicationStatement.

**Comment by ziegm** [comment]
- changes in branch [issue17](https://github.com/ehealthsuisse/ch-emed/tree/issue17)
- Correction of section.text.table in CDA documents (2-7, 2-3) done, see [commit](https://github.com/hl7ch/hl7ch-cda/commit/10875399651190669f91e218b2acff1d65eb62f9)
