### ISSUE TITLE
document.typeCode wrong displayname (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#18]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-composition-medicationprescription.html

composition.type.coding.display has Fixed Value: Medical Prescription record (record artifact) ->> change to MediCInal Prescr ... as in SNOMED CT https://browser.ihtsdotools.org/?perspective=full&conceptId1=761938008&edition=MAIN/2021-01-31&release=&languages=en
annex 3 was wrong, will be corrected, artdecor already updated with correct display name: http://ehealthsuisse.art-decor.org/ch-epr-html-20200622T124207/voc-2.16.756.5.30.1.127.3.10.1.27-2020-02-26T173448.html

Annatina Foppa, eHealth Suisse

**Comment by annatinafoppa** [comment]
unfortunately, this correction of wrong display name has not been accepted. Value has to remain "Fixed Value: Medical Prescription record" to be in alignment with annex 3.
hopefully, we can change this in a next revision of annex 3.
->> Issue can be closed

**Comment by eHealth-Suisse** [comment]
ticket remains open until FHIR WG meeting

**Comment by oliveregger** [comment]
suggest that we remove the pattern matching on the display code, system and code is sufficient
