### ISSUE TITLE
medication.ingredient.itemCodeableConcept.text : description and cardinality are not consistent (annatina foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#20]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medication-medicationstatement.html

the description says: "	If no code ist available, the text should indicate the ingredient name" ... but the cardinality 1...1 implies that text is always required, regardless of if there is a code or not

annatina foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
> either change description or cardinality
> hints from CDA-CH-EMED or IPAG report available?

**Comment by oliveregger** [comment]
https://art-decor.org/art-decor/decor-templates--cdachemed-?id=2.16.756.5.30.1.1.10.4.34&effectiveDate=dynamic
-> name is required if an ingredient is provided(pharm:name | TN | 1 … 1 | R)

this is the same. IPAG also requires: 
Wirkstoffname | e/o | C | Entweder Präparat oder Wirkstoff(e) muss deklariert sein

suggest to correct text to just: ingredient name
