### ISSUE TITLE
medication.code: cardinality should be 0 ...1 (annatina foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#21]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medication-medicationstatement.html

it should be possible to only indicate the ingredient without a code for a medication which is now required (1...1)

annatina foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
>change Medication.code to 0..1
> check if there are implications on following items/cardinalities

**Comment by oliveregger** [comment]
change Medication.code to 0..1

**Comment by oliveregger** [comment]
medication for request and statement were the same -> merged
medication for dispense -> constraint from ch-emed medication and added the additional elements

added a business constraint that either medication name or ingredient name has to be specifed.
