### ISSUE TITLE
2-7 Medication Card document - XML Representation (Input from Walter Wellauer during eMedication Projectathon)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#22]
ch.fhir.ig.ch-emed#0.2.0 /Bundle-2-7-MedicationCard.xml.html

The example does not define the unit/code of the doseQuantity (Tablets). 

Input from Walter Wellauer during eMedication Projectathon

**Comment by eHealth-Suisse** [comment]
some changes already made during eMed Projectathon
