### ISSUE TITLE
CH EMED Medication Profile - amount / ingredien.strength with uni (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#23]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medication-medicationstatement.html

Medication.amount and Medication.ingredient.strenght are of Type Ratio where you have numerator and denominator as Quantity. These elements should also be constrained by http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-quantity.html that the units are defined accordingly.   

This would apply to all Medication Profiles.

This is related also to https://github.com/ehealthsuisse/ch-emed/issues/22

Oliver Egger, ahdis

**Comment by eHealth-Suisse** [comment]
agree, was made similarly with CDA-CH-EMED, see also issue no. 17 on CH-PHARM https://art-decor.org/art-decor/decor-issues--ch-pharm-

**Comment by oliveregger** [comment]
check with cda resolution of  https://art-decor.org/art-decor/decor-issues--ch-pharm-?id=2.16.756.5.30.1.127.77.4.6.17&language=en-US
