### ISSUE TITLE
2-7 Medication Card document PDF representation is not correct (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#25]
ch.fhir.ig.ch-emed#0.2.0 /Bundle-2-7-MedicationCard.html

The PDF representation for the FHIR (and also CDA) example contains a dosis per unit of 2.5mg but this is in the source 50 mg / unit for Beloc Zok Metoprolol.

See https://ehealthsuisse.ihe-europe.net/gazelle/testing/test/test/TestInstance.seam?id=39290&cid=354975

PDF can be extracted with https://base64.guru/converter/decode/pdf 

Oliver Egger, ahdis

**Comment by eHealth-Suisse** [comment]
> to fix, see also #17 for other correction on PDF example

**Comment by ziegm** [comment]
Fixed in FHIR: see [commit on CH EMED](https://github.com/ehealthsuisse/ch-emed/commit/bd8b10b084ed659237622f1cf65af51544a68032)
Fixed in CDA: TBD
