### ISSUE TITLE
CH EMED MedicationStatement Identifier as uuid required (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#26]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medicationstatement-card.html

Currently the MedicationStatement.identifier is 0..*, however we need to have a unique uuid to identify this MedicationStatement in the exchange format (see CDA-CH-EMED: https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.4.34&effectiveDate=2019-12-11T11:31:52&language=en-US). Propose to require one identifier with a uuid (system fixed).

This would also apply to MedicationRequest, MedicationDispense and Observation (for Pharmaceutical Advice).

In addition the document itself needs also uuid as an identifier, since this is related to all EPR exchange format this has been added as a CH-Core issue, see https://github.com/hl7ch/ch-core/issues/95

Oliver Egger, ahdis

**Comment by eHealth-Suisse** [comment]
agree
