### ISSUE TITLE
specify data elements for original representations (annatina foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#29]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-composition-medicationcard.html

out of discussion from eMed-Projectathon: 
- for a start, PDF representation should only be required on Medication Card document which is also the first document to enter the EPR legal framework
- what this PDF has to include (at minimum) should be defined, probably in discussion with interprofessional group IPAG

annatina foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
first point already covered in #28 , PDF required on Medication Card AND Prescription
second point should be adressed in discussion with health care professionals

**Comment by annatinafoppa** [comment]
Question passed on to IPAG (IPAG meeting of 15.4., desired response deadline by 26.5.)

**Comment by eHealth-Suisse** [comment]
Unfortunately, we haven't received an answer from IPAG in time. 
Proposition: required elements in PDF according to Minimal data set in IPAG report. Concerns Medication Card document.

**Comment by eHealth-Suisse** [comment]
as soon as we get an answer from IPAG, we can change this requirement if necessary; but it will be too late for the upcoming release

**Comment by ziegm** [comment]
As discussed with Annatina, a note has been added to the Medication Card document that the required elements correspond to the IPAG-MDS and that these elements are flagged with mustSupport = true in the FHIR profiles.
