### ISSUE TITLE
UnitsOfPresentation -- different issues (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#30]
ch.fhir.ig.ch-emed#0.2.0 /ValueSet-UnitsOfPresentation.html

see discussions during eMed Projectathon, Pero Grgic knows the current state

Annatina Foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
see issue #38  and CH-Pharm-Issue No. 19 https://art-decor.org/art-decor/decor-issues--ch-pharm-

**Comment by eHealth-Suisse** [comment]
duplicate of now closed issue #38
