### ISSUE TITLE
set "must support" flags (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#31]
ch.fhir.ig.ch-emed#0.2.0 /

to define which elements have to be "understood" by implementing systems

Annatina Foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
for further explanation see the example of IPS, https://build.fhir.org/ig/HL7/fhir-ips/design.html#must-support

**Comment by oliveregger** [comment]
1) according to IPAG data elements
2) swiss emedication architecture table with supported data elements in pdf 7.2 CDA-CH-EMED and CH-EMED Key Element

-> mustSupport should be a mix of th two?

**Comment by ziegm** [comment]
Current status:

- [Mapping table eMedication](https://docs.google.com/spreadsheets/d/1Ui3NGFE2I8yiOlHELk-B0Pke2l9-Jbe5BTeYOnS8-uE/edit#gid=1859696266)
   - add mapping of the data elements from section *7.2 CDA-CH-EMED and CH-EMED Key Elements* (p. 136) from the PDF [Implementation Guide for eMedication architecture in the context of the EPR - Detailed specification, Version 0.13](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/E/Implementation_Guide_eMedication_Architecture_Specs_013_Anhoerung.pdf)

- IG CH EMED (branch must-support):
   - Set MustSupport for the "green" [IPAG](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/2017/D/170607_Bericht_eMedikation_IPAG.pdf) elements for
      - Medication Card document
