### ISSUE TITLE
UnitsOfPresentation (Priska Vonbach, PEDeus AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#32]
ch.fhir.ig.ch-emed#0.2.0 /ValueSet-UnitsOfPresentation.html

Der Begriff "actuation" kann sowohl für einen Hub (Lösung) als auch für einen Sprühstoss (Aerosol) stehen. Die Übersetzungen "Betätigung (Sprühstoss)" sowie "bouffée" lassen jedoch nur die Verwendung als Einheit für ein Aerosol zu. Damit steht aber keine Einheit für z.B. eine orale Lösung (wie Tramal mit Dosierpumpe oder auch Flatulex) zur Verfügung. Wir bitten um Übersetzungen auf derselben "Ebene". Konkret sollte die Klammerbemerkung bei der Deutschübersetzung weggelassen werden, also lediglich "Betätigung" (allenfalls ginge auch Hub, weil Hub sowohl für eine Dosierpumpe als auch für ein Aerosol gebraucht wird). Im Französischen darf es ebenfalls nicht "bouffée" sein - da können wir aber keinen konkreten Vorschlag machen (dazu braucht es einen französischsprechenden Experten), Unklar ist für uns auch, ob die italienische Übersetzung sowohl für Aerosole als auch Lösungen gebraucht werden kann. Für allfällige weitere Erklärungen stehe ich gerne zur Verfügung.

Priska Vonbach, PEDeus AG

**Comment by eHealth-Suisse** [comment]
vgl. auch issues #24 und #38 , betreffen das gleiche Value Set
betreffend französische Übersetzung: kommt von SNOMED, als Alternative gäbe es noch "pression". vermutlich braucht es eher ein zusätzliches Konzept als eine zusätzliche Übersetzung ->> zu diskutieren, weitere Abklärungen nötig

**Comment by eHealth-Suisse** [comment]
Die Übersetzung von "actuation" wird angepasst. Es werden zwei Synonyme erstellt. Ein Synonym mit "Hub" als preferred und ein Synonym "Sprühstoss" als accepted.

**Comment by eHealth-Suisse** [comment]
angepasst, siehe https://art-decor.org/art-decor/decor-valuesets--ch-pharm-?id=2.16.756.5.30.1.1.11.83&effectiveDate=2021-02-10T22:24:02&language=en-US
