### ISSUE TITLE
CH EMED Observation Profile (Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#33]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-observation.html

The CH EMED Observation Profile used in the Pharmaceutical Advice should be able to change the strucutred dosage for a referencing Medication Treament Plan. As a proposal we could create a "contained" MedicationStatement that is referenced inside the "partOf" Attribut of the CH EMED Observation Profile.

Cistec AG

**Comment by eHealth-Suisse** [comment]
needs to be clarified if possible and what way would be best

**Comment by oliveregger** [comment]
same information needs to be transmitted cda pdav

**Comment by ziegm** [comment]
### Additional use case to show how the dosage can be changed

- Initial situation:  [1-1 Medication Treatment Plan document](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/master/Bundle-1-1-MedicationTreatmentPlan.html)
  Triatec: 0.5-0-0-0

- Dosage change: [Pharmaceutical Advice document - Change Dosage](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue33/Bundle-PharmaceuticalAdvice-ChangeDosage.xml.html)
   Triatec: 1-0-0-0

- Profile [Observation](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue33/StructureDefinition-ch-emed-observation.html)
   - added [Extension](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue33/StructureDefinition-ch-emed-ext-medicationstatement-changed.html) to reference the changed MedicationStatement 
   - Comments to the proposal above:
      - Observation.partOf
         - [FHIR Definition](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue33/StructureDefinition-ch-emed-observation-definitions.html#Observation.partOf) = A larger event of which this particular Observation is a component or step. For example, an observation as part of a procedure.
         - Observation is rather the larger event and the new MedicationStatement a component of it. Therefore, an extension was added instead of using this element.
      - "contained" MedicationStatement:  
         - The changed MedicationStatement is represented as a Bundle.entry (referenced from Observation.extension) and not as a contained resource in Observation. It is an independent and complete MedicationStatement.

- see also [IHE_Pharmacy_Suppl_PADV](https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_PADV.pdf)
    - 6.3.4.3.3.12 Changed Medication Treatment Plan Item (page 39)
    - Community Pharmaceutical Advice CDA Document (page 16)

**Comment by eHealth-Suisse** [comment]
next steps:
- validate CDA (Michaela)
- talk to Quentin (Annatina)
- ask Walter for feedback @walterwellauer
- discuss in the working group 2.6.

**Comment by ziegm** [comment]
[CDA validation](https://ehealthsuisse.ihe-europe.net/EVSClient//detailedResult.seam?type=CDA&oid=1.3.6.1.4.1.12559.11.25.1.13.48414&privacyKey=Jzmgcd06KH1cvoWp):
* E-1: no original representation in CDA document
* E-2 to E-17: 'substanceAdministration' is defined as closed, and this element 'xxx' is not allowed, or not allowed with this content. This may concern the templateId, code or id. Expected in this context: hl7:templateId[@root = '1.3.6.1.4.1.19376.1.9.1.3.7'] (rule-reference: d265989e15-true-d266227e0)
   * Quentin: should this be open instead of closed or isn't the example correct or how are this errors to handle?

**Comment by qligier** [comment]
E-2 to E-17: This Schematron rule is completely bogus. I'd rather leave the template as closed and prevent the rule from being generated. It's tracked in https://art-decor.org/art-decor/decor-issues--ch-pharm-?id=2.16.756.5.30.1.127.77.4.6.43.

**Comment by ziegm** [comment]
> E-2 to E-17: This Schematron rule is completely bogus. I'd rather leave the template as closed and prevent the rule from being generated. It's tracked in https://art-decor.org/art-decor/decor-issues--ch-pharm-?id=2.16.756.5.30.1.127.77.4.6.43.

Thank you for the feedback!

**Comment by ziegm** [comment]
Added purposes and links to the PADV examples in the document tab:   
http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue33/pharmaceutical-advice-document.html

**Comment by eHealth-Suisse** [comment]
solution presented in FHIR Work group on 2nd of June, https://github.com/hl7ch/ch-core/wiki#wed-02062021-telco-hl7ch-fhir-work-group-200-pm---300-pm
no further comments; ticket will be closed.
ticketissuer @walterwellauer for information and potential objections.
