### ISSUE TITLE
CH EMED Medication Card Composition Profile - Annotation section.entry.reference 1..1? (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#34]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-composition-medicationcard.html

Why is the cardinality of the Annotation section.entry.reference 1..1? In the example no entry.reference is specified.

Oliver Egger, ahdis

**Comment by eHealth-Suisse** [comment]
agree that it is unclear. other hint that it is not required to be 1..1 : Annotation section.entry.identifier says "Logical reference, when literal reference is not known" meaning that there can be cases without literal reference (= entry.reference).
maybe something that comes from the CDA translation?
If no indication for 1..1 is found : change to 0..1
