### ISSUE TITLE
CH EMED Dosage Structured Profile (MedicationStatement / MedicationDispense) -  define EventTiming for 1-1-1-1 dosing (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#35]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-dosage-structured.html

TiminEvent: Our "Swiss" dose time regime, like 1 - 1 - 1 -1 as TimingEvent, How should it be coded? There is also the open issue mentioned here (https://art-decor.org/art-decor/decor-issues--ch-pharm-?id=2.16.756.5.30.1.127.77.4.6.20&language=en-US)

CDA-CH-EMED / CH EMED examples:
ACM - ACD- ACV - HS

Cistec:
CM", "CD", "CV", "HS"

Oliver Egger, ahdis

**Comment by drats-cis** [comment]
Zur Auswahl stehen folgende TimingEvents: https://terminology.hl7.org/1.0.0/CodeSystem-v3-TimingEvent.html
Der deutsche Medikationsplan verwendet: https://simplifier.net/medikationsplanplus/einnahmezeitpunkte-1
Aus klinischer Sicht wäre je nach Medikament die Möglichkeit, strukturiert "vor dem Essen", "zum Essen" oder "nach dem Essen" zu erfassen, durchaus sinnvoll. Somit wären alle diese Schemen wünschenswert:.
ACM - ACD- ACV - HS
  CM -   CD-   CV - HS
PCM - PCD- PCV - HS
Bei einem Grossteil der Medikamente spielt es aber kaum eine Rolle, dort würden wir als Defaultwert ohne A (ante) und P (post) codieren, wie in Deutschland.
Daniel Ratschiller, Cistec AG

**Comment by eHealth-Suisse** [comment]
es stehen noch mehr als die genannten Events zur Auswahl, nämlich: https://www.hl7.org/fhir/valueset-event-timing.html (besteht aus fast dem vollständigen v3-Timing-Event-Value-Set plus noch zusätzliche Codes wie "MORN", "NOON" etc)
mit Cara (Haupt-CDA-Nutzerin) wurde diskutiert, das v3-Value-Set mit diesem breiteren Value-Set zu ersetzen (vgl. Link Art-Decor oben). Das Event-Timing-Value-Set von FHIR ist "required"

**Comment by oliveregger** [comment]
TimingEvents sind alle erlaubt, im IG machen wir aber eine explizite Empfehlung jetzt:

http://build.fhir.org/ig/ehealthsuisse/ch-emed/dosage.html
For the representation of the time of administration according to the 1-1-1-1 scheme, the values MORN-NOON-EVE-NIGHT from the ValueSet EventTiming are highly recommended for the Swiss use.

**Comment by eHealth-Suisse** [comment]
Umsetzung wie am 25.5.21 besprochen, herzlichen Dank! Ticket geschlossen
