### ISSUE TITLE
subject Reference(CH Core Composition Patient Profile EPR|CH Core Patient) (Walter Wellauer, Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#36]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medicationstatement-treatmentplan-definitions.html
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medicationrequest-definitions.html
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medicationdispense.html
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-observation.html
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medicationstatement-card-definitions.html

#%.subject should reference CH Core Composition Patient Profile EPR or CH Core Patient for all the above metioned profiles to be able to be referenced / integrated in other CH Profiles like CH AllergyIntolerance, CH VACD, CH eTransitionOfCare, CH t.b.d.
#MedicationStatement.subject 
#MedicationRequest.subject
#MedicationDispense.subject
#Observation.subject
The constraint to CH Core Composition Patient Profile EPR should be achieved on the composition level with FHIR Path rules or similar
If not every clinical profile has to be duplicated for B2B and other Swiss use cases which makes it much harder for conistent maintenance and usablitly

Walter Wellauer, Cistec AG

**Comment by eHealth-Suisse** [comment]
similar request also with CH-VACD -> discussion in FHIR WG from 24 march

**Comment by walterwellauer** [comment]
A solution could be applying GraphDefinitions:
https://www.hl7.org/fhir/graphdefinition.html
5.9.1 Scope and Usage
(...)
•	Document rules about the relationship between a set of resources e.g. must all resources concern the same patient?

So via the composition it could be controlled, that same patient (profile) is referenced in the referenced entries as (e.g.) in http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-composition-medicationtreatmentplan-definitions.html#Composition.subject

There is even an example for that under the above mentioned hyperlink:

  <link>
    <path value="Composition.section.entry"/>
    <target>
      <type value="List"/>      
        <compartment>
          <use value="requirement"/>
          <code value="Patient"/>
          <rule value="identical"/>
        </compartment>
      </target>
      <link>
        <path value="List.entry.item"/>
        <description value="Include any list entries"/>
        <target>
          <type value="Resource"/> 
          <compartment>
            <use value="requirement"/>
            <code value="Patient"/>
            <rule value="identical"/>
          </compartment>
        </target>
      </link>      
    </target>
  </link>

**Comment by oliveregger** [comment]
* grahdefinition is not implemented yet in the IG Publisher/Validator tooling
* %.subject should only reference to CH Core Patient that it can be reused for any situation in Switzerland as @walterwellauer has described except in the composition for the EPR exchange format where we want to have in addition the rules for CH Core Patient EPR included.

**Comment by oliveregger** [comment]
schedule for hl7 fhir.ch telco https://github.com/hl7ch/ch-core/wiki

**Comment by oliveregger** [comment]
resource auf ch-core referenzieren und die epr profil version nur wenn notwendig (nicht beide aufführen)

**Comment by ziegm** [comment]
### Following checks are done:

**CH Core Patient Profile EPR** only on Composition level: 
- Composition.subject
- Composition.author
- Composition.section.author   

or in the context of the Medication Card document:
- MedicationStatement(Card).extension:ch-emed-ext-documentauthor



**CH Core Profiles** are used as references, where a Swiss profil exists.
- MedicationStatement (MTP)
- MedicationStatement (Card): [references to CH Core (not CH Core EPR) unified](https://github.com/ehealthsuisse/ch-emed/commit/db621eb65d0480a529f8342840034756a80b6dc3)
- MedicationRequest
- MedicationDispense
- Observation

********************

The checks were made for the specified and used elements in the CH EMED exchange format (Differential Table).   

Decision taken during the CH Core ballot:
_guidelines next ballot: define policy that for all references which are not defined as a datatype the relationship to ch-core has to be profiled or it has to be made explicit if there is a reason._ See comment [here](https://github.com/hl7ch/ch-core/pull/108#issuecomment-814906508).
