### ISSUE TITLE
CH EMED Quantity with units: 1..1 (Walter Wellauer, Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#37]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-quantity.html

Coded quantity should be mandatory to minimize possible mismatch with patient risk

Walter Wellauer, Cistec AG

**Comment by walterwellauer** [comment]
Quantitiy
  code |   | 1..1 | code Coded form of the unit Binding: UnitsOfPresentation (required): The unit used describing the quantity.

**Comment by eHealth-Suisse** [comment]
agree in principle, but implications should be checked first (for example on denominator [see also #23], could be too strong)

**Comment by walterwellauer** [comment]
as shown in the projeactathon testings in September as well as recently in March it may be very dangerous for the patient and in the worst case even provoke a possible CIRS case if non coded medication units are allowed to be interchanged
