### ISSUE TITLE
UnitsOfPresentation (Daniel Ratschiller, CISTEC AG)

### ISSUE THREAD

**Issue by drats-cis** [ehealthsuisse/ch-emed#38]
http://build.fhir.org/ig/ehealthsuisse/ch-emed/ValueSet-UnitsOfPresentation.html
To substantiate my comments in #24, I share here another Excel file with the analyses made.
- It contains some potential missing galenic forms.
- It shows a shortlist of units from our HIS that has emerged in Switzerland over 20 years.
- With the value sets of units and galenic forms as used in the Hospindex.
- With an analysis of how often these units and galenic forms are used in the Hospindex products.

[UnitsOfPresentation_HCI_Einheiten_Galenische_Form_Ballot.xlsx](https://github.com/ehealthsuisse/ch-emed/files/6144080/UnitsOfPresentation_HCI_Einheiten_Galenische_Form_Ballot.xlsx)

**Comment by eHealth-Suisse** [comment]
Thank you, @drats-cis, for this detailed analysis! issues need further inquiries, see also other tickets referenced

**Comment by annatinafoppa** [comment]
Besprochen am 23.4.2021 mit Lisa Riedl und Daniel Ratschiller:
- «Retard-Tablette» gehört nicht rein, ist eine medizinische Information und gehört zu EDQM. 
- «Set» zu spezifisch, wird nicht aufgenommen
- Aus Konsistenzgründen wird deshalb «Lutschtablette» entfernt

**Comment by eHealth-Suisse** [comment]
umgesetzt, siehe https://art-decor.org/art-decor/decor-valuesets--ch-pharm-?id=2.16.756.5.30.1.1.11.83&effectiveDate=2021-02-10T22:24:02&language=en-US
