### ISSUE TITLE
At least coded active drug ingredients (Daniel Ratschiller, CISTEC AG)

### ISSUE THREAD

**Issue by drats-cis** [ehealthsuisse/ch-emed#39]
We would like to put forward the following proposal for discussion: In order to do something against a free-text medication registration, which is rather undesirable in the structured medication transmission, the coding of medications could be required as follows: 

If no GTIN or pharmaceutical code is available for an article, then at least the active ingredients should have to be indicated in coded form (by means of SCT substance codes). 

Such a constraint could be modelled as follows: 
 : code.coding.where(system = urn:oid:2.51.1.1).exists() or ingredient.exists()

Can you please check this out?

**Comment by eHealth-Suisse** [comment]
has to be checked. see also similarities to #21 
what about use cases where neither a GTIN is available nor the ingredient is to be found in the coded substances?

**Comment by annatinafoppa** [comment]
Question passed on to IPAG (IPAG meeting of 15.4., desired response deadline by 26.5.)

**Comment by eHealth-Suisse** [comment]
Unfortunately, we haven't received an answer from IPAG in time. Decision: for the next release, we leave the spec as it is. Ticket will be closed, answer of IPAG will be introduced into next ballot in case it leads to changes.
At ticket issuer @drats-cis for information
