### ISSUE TITLE
CH EMED: Fixed Values for system in codings don't allow multiple codings (annatina (based on Ticket by Michaela from Projectathon 2020))

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#40]
ch.fhir.ig.ch-emed#0.2.0 /StructureDefinition-ch-emed-medication-medicationstatement.html

In different codings are the system as "fixed Value" defined. This way multiple codings with different systems are not allowed. This should be changed, so that it is possible.

e.g.: Medication.code.coding
http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medication-medicationstatement.html

Where this issue is present everywhere, needs to be reviewed.

annatina (based on Ticket by Michaela from Projectathon 2020)

**Comment by eHealth-Suisse** [comment]
yes, needs to be reviewed

**Comment by oliveregger** [comment]
http://localhost:52330/output/Bundle-MedicationCard-DifferentAuthors.json.html has a local code/local system in the medication and this works (slice is open). do we have an example where it does not work @ziegm ?

**Comment by ziegm** [comment]
This issue has already been solved: https://github.com/ehealthsuisse/ch-emed/issues/6
