### ISSUE TITLE
Profiles in IG

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-emed#50]
Profile Tab: show profile list (equivalent to ch-core)
Profile according to documents -> move to document tabs

**Comment by ziegm** [comment]
Solved: See tab [Profiles](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/master/profiles.html) and tab Documents (for example [Medication Card document](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/master/medication-card-document.html))

**Comment by eHealth-Suisse** [comment]
merci @ziegm . sind die data type profiles absichtlich nicht bei den profiles aufgeführt? ich suche häufig nach dem dosage-profil ... aber kann auch damit leben, es bei den artifacts zu holen, falls nur ressourcen-profile angezeigt werden sollen

**Comment by ziegm** [comment]
@annatinafoppa: soll ich sie noch ergänzen? sonst kannst du immer gerade über die medication zur dosage. 
die datentypen quantity, range, ratio würde ich aber nicht aufführen oder?

**Comment by eHealth-Suisse** [comment]
ja, wenn das nicht gegen die FHIR-Politik verstösst, dann gern. Genau, nur die ersten drei Dosage-Profile. quantity, range, ratio nicht.
