### ISSUE TITLE
Übersetzung Timing Event (fehlende Begriffe)

### ISSUE THREAD

**Issue by eHealth-Suisse** [ehealthsuisse/ch-emed#51]
http://hl7.org/fhir/R4/valueset-event-timing.html
Teilweise bereits übersetzt in CDA.
Mit CodeSystem Supplement https://www.hl7.org/fhir/codesystem.html#supplements lösen.

**Comment by eHealth-Suisse** [comment]
in Auftrag gegeben, folgt bis 26.5.

**Comment by oliveregger** [comment]
Codes sind hier: http://hl7.org/fhir/R4/codesystem-event-timing.html

**Comment by eHealth-Suisse** [comment]
Übersetzungen sind im ArtDecor eingepflegt: https://art-decor.org/art-decor/decor-valuesets--ch-pharm-?id=2.16.756.5.30.1.127.77.4.11.2&effectiveDate=2020-07-10T00:28:08&language=en-US.
Lasse Ticket noch offen, weil @oliveregger du das noch als supplement hinzufügst?

**Comment by oliveregger** [comment]
Supplement ist hinzugefügt: http://build.fhir.org/ig/ehealthsuisse/ch-emed/CodeSystem-v3-TimingEvent.html
