### ISSUE TITLE
CH EMED Dosage Structured Profile (MedicationStatement / MedicationDispense) (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#53]
ch.fhir.ig.ch-emed#0.3.0 /StructureDefinition-ch-emed-dosage-structured.html

We should make the dosage type required if no text is provided (business constraint), otherwise we don't know if it corresponds to a normal, split or tapered dose.

see also https://github.com/hl7ch/cda-fhir-maps/issues/24

Oliver Egger, ahdis

**Comment by oliveregger** [comment]
currently supported is only normal and split dosing, if multiple dosages appear, split dosing is assumed. therefore the cda template id's are not required for the dosage type
