### ISSUE TITLE
CH EMED Medication List Composition Profile (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#54]
ch.fhir.ig.ch-emed#0.3.0 /StructureDefinition-ch-emed-composition-medicationlist.html

Composition.title und  Composition.section:list.title heissen auf Englisch beide "Medication List", auf Deutsch/Französisch/Italienisch sind aber unterschiedliche Übersetzungen angegeben. Ist das Absicht und relevant? 

Composition.title : 	'Medikationsliste' in german or 'Liste de médication' in french or 'Elenco delle terapie farmacologiche' in italian or 'Medication List' in english or titles in other languages are also allowed

Composition.section:list.title : 	'Medikamentenliste' in german or 'Liste de médicaments' in french or 'Lista farmaci' in italian or 'Medication List' in english or titles in other languages are also allowed

Bei anderen Doks teilweise auch so, habe aber nicht systematisch überprüft.
http://build.fhir.org/ig/ehealthsuisse/ch-emed/StructureDefinition-ch-emed-composition-medicationlist.html 

Annatina Foppa, eHealth Suisse

**Comment by ziegm** [comment]
Das kommt von der CDA-Spezifikation.

Composition.title = ClinicalDocument.title (z.B. "Medikationsliste")
https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.1.13&effectiveDate=2018-01-22T15:17:26&language=en-US

Composition.section.title = section.title (z.B. "Medikamentenliste")
https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.3.44&effectiveDate=2018-01-22T15:40:38&language=en-US

**Comment by eHealth-Suisse** [comment]
Danke für Erläuterung. Für das Medication Card document im Speziellen überprüft (in CDA-Spez), ist akzeptabel. Schliesse Ticket.
