### ISSUE TITLE
CH Core Composition Profile: version number should be required

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-emed#55]
In [CHCoreCompositionEPR](http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-composition-epr-definitions.html#Composition.extension:versionNumber), the version number is optional. It's required in [CDA-CH-EMED](https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.1.13&effectiveDate=2018-01-22T15:17:26&language=en-US).

**Comment by oliveregger** [comment]
This is handled in the mapping because FHIR document bundle does not have the same versioning princip. If it is provided in CDA-CH-EMED it will be mapped to the version (which is an extension). If a FHIR document has no version set,  it will be mapped to the first version in CDA.

**Comment by qligier** [comment]
Ok, that makes sense. Thanks!
