### ISSUE TITLE
mapping überprüfen zu repeat number

### ISSUE THREAD

**Issue by eHealth-Suisse** [ehealthsuisse/ch-emed#56]
altbekanntes Ticket: https://art-decor.org/art-decor/decor-issues--ch-pharm-?id=2.16.756.5.30.1.127.77.4.6.6&language=en-US
mir RepeatNumber required. NullFlavor hat dabei die Bedeutung "unlimited repeat/refill". Ist das im Mapping bzw. in der FHIR Specs schon berücksichtigt?

**Comment by oliveregger** [comment]
it is set now to NI if it has to be set in the mapping.
