### ISSUE TITLE
Composition sections should be ordered (oe, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#57]
ch.fhir.ig.ch-emed#0.3.0 /StructureDefinition-ch-emed-composition-medicationtreatmentplan.html

The sections in the documents should have fix order equivalent to CDA-CH-EMED:

1. Medication Treatment Plan Section Content Module (or other depending on document)
2. Remarks Section - coded (DYNAMIC)
3. Original Representation Section - coded (DYNAMIC)

oe, ahdis

**Comment by oliveregger** [comment]
cannot be fixed currently in ch-emed due to inherited constraints (see issue above), but example will be fixed.

**Comment by qligier** [comment]
Is this about the documentation pages only? As discussed during the last projectathon, the order of these sections is free in CDA-CH-EMED documents.

**Comment by oliveregger** [comment]
@qligier : do you mean with documentation pages Remarks Section - coded (DYNAMIC)
and Original Representation Section?

**Comment by qligier** [comment]
The three `component`s _(MTP/PRE/DIS/PADV) Section Content Module_, _Remarks Section_ and _Original Representation Section_ are allowed in any order in CDA-CH-EMED documents, so I'm not sure what you meant by saying "_[...] fix order equivalent to CDA-CH-EMED_".

**Comment by oliveregger** [comment]
closed after feedback from @qligier
