### ISSUE TITLE
CH EMED Dosage Structured Profile (MedicationStatement / MedicationDispense) (oe, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#58]
ch.fhir.ig.ch-emed#0.3.0 /StructureDefinition-ch-emed-dosage-structured.html

Structured Dosage can be of different types. 

For normal dosing one Structured Dosage is required, for split dosing (any probably also tapered) multiple dosages with a sequence number can be provided. 

Proposition to create two profiles, one for NormalStructuredDosage (max 1 and no sequence number set) and one for SplitStructure Dosage (multiple and sequenceNumber set).

oe, ahdis

**Comment by ziegm** [comment]
Added tab [Dosage](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/master/dosage.html) in IG
