### ISSUE TITLE
mustSupport for Required item's in Medication Card Composition? inconsistent handling (Oliver Egger, ahdis ag, original feedback by Rob)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#62]
ch.fhir.ig.ch-emed#1.0.0 /StructureDefinition-ch-emed-composition-medicationcard.html

Oliver Egger, ahdis ag, original feedback by Rob

**Comment by oliveregger** [comment]
> Also, I did have a look at the specs and they look good (of course I’m still making my way through them).  I like some of the changes.  I did have one question.  When looking at the Medication Care Composition Profile, I saw that the section, card, and annotations had that nifty (must support icon).  I was curious why the OriginalRepresentation didn’t have it as well?  I thought the pdf was required.  The cardinality still has it as 1..1

Yes mustSupport is for the optional elements which "must be supported" in addition to the required ones. However I have seen now that

1. this is not consistent in the medication card where originalRepresentation is 1..1 and not mustSupoprt but section:card is 1..1 in addition with mustSupport.
2. the mustSupport does only show the Snapshot Table (Must Support) with mustSupport elements, I thought that included also required, either the IG Publisher changed that.

http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-composition-medicationcard.html

Differential table:

![image](https://user-images.githubusercontent.com/2414516/123070496-19aaf200-d414-11eb-8432-9d60f2158df6.png)


Snapshot (MustSupport) Table:

![image](https://user-images.githubusercontent.com/2414516/123070533-23345a00-d414-11eb-9e0d-f29e3d59b7de.png)

**Comment by ziegm** [comment]
As additional information for this issue the actual situation:

[Description in IG](http://fhir.ch/ig/ch-emed/medication-card-document.html):   
_The representation of the Medication Card document SHALL be embedded as a PDF in PDF/A-1 or PDF/A-2 format. The required elements in the PDF correspond to the minimum data set in the IPAG report. In the FHIR profiles, the flag mustSupport is set to true for these elements._

**Comment by oliveregger** [comment]
I propose that we need to provide a separate paragraph on the mustSupport in a next step and put it on the front page of the ig.

'The flag mustSupport requires that a creator and the consumer MUST support these elements if known. The mustSupport flag has been derived from the elements marked as the minimum data set in the IPAG report'

**Comment by ziegm** [comment]
The flag mustSupport requires that the creator and the consumer MUST support these elements if they are known. 
-> Anpassen an CH Core Diskussion 03.11.
Required if known for creator (not consumer)

2 Abschnitte auf Home
Bedeutung Flag Must Support (CH Core)
Meaning for Original Representation

**Comment by ziegm** [comment]
Composition.section:originalRepresentation = MS true

**Comment by ziegm** [comment]
@pjolo 
Please review the [change](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue62/index.html#mustsupport) and if it is okay, please merge this [pull request](https://github.com/ehealthsuisse/ch-emed/pull/82) and close the issue.
