### ISSUE TITLE
CH EMED Extension Substitution - ValueSets not equal to CDA (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#65]
ch.fhir.ig.ch-emed#1.0.0 /StructureDefinition-ch-emed-ext-substitution.html

Substitution of the medication
Binding: ActSubstanceAdminSubstitutionCode (preferred)

Points to the HL7 V3 ValueSet: https://terminology.hl7.org/2.1.0/ValueSet-v3-ActSubstanceAdminSubstitutionCode.html which contains the code F (Formulary), the code F is not within https://art-decor.org/art-decor/decor-valuesets--ch-pharm-?id=2.16.756.5.30.1.1.11.81&effectiveDate=2020-07-10T00%3A52%3A42

Oliver Egger, ahdis

**Comment by oliveregger** [comment]
Value “F” from the substitution value set was removed because there was no usage in Switzerland,

**Comment by ziegm** [comment]
Feedback eHS: Wert "F" kann wieder aufgenommen werden
