### ISSUE TITLE
MedicationDispense: languageCode fr-CH not accepted (Oliver Egger and Dan Joguet-Laurent)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#68]
ch.fhir.ig.ch-emed#1.0.0 / languageCode fr-CH not accepted

We encountered an issue when validating languageCodes fr-CH in MedicationDispense. We added a PR to demonstrate the behaviour directly in the IG, see [PR](https://github.com/ehealthsuisse/ch-emed/pull/67)

Oliver Egger and Dan Joguet-Laurent

**Comment by oliveregger** [comment]
Changing the language type is not enough, in addition the titles etc needs to be changed. Therefore it is not an issue with the specification but with the provided sample.

The next version of the validator will indicate with more detailed while the validation was not successful:

>This element does not match any known slice defined in the profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationdispense Slice info: 1.) Bundle.entry[0]: Does not match slice 'Composition' 2.) Bundle.entry[0]: Bundle.entry[0].resource.title: ch-emed-title-dis: ''Abgabe' in german or 'Remise' in french or 'Dispensazione' in talian or 'Dispense' in english                         or titles in other languages are also allowed' Rule ''Abgabe' in german or 'Remise' in french or 'Dispensazione' in talian or 'Dispense' in english                         or titles in other languages are also allowed' Failed 3.) Bundle.entry[0]: Bundle.entry[0].resource.section[0].title: ch-emed-sect-dis: ''Abgabe eines Medikaments' in german or 'Dispensation d'un médicament' in french or 'Dispensazione di un medicamento' in talian or 'Medication dispensed' in english                         or titles in other languages are also allowed' Rule ''Abgabe eines Medikaments' in german or 'Dispensation d'un médicament' in french or 'Dispensazione di un medicamento' in talian or 'Medication dispensed' in english                         or titles in other languages are also allowed' Failed 4.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).extension[0]: Bundle.entry[6].resource.ofType(MedicationDispense).extension[0]: Does not match slice 'treatmentReason' 5.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).extension[0]: Bundle.entry[6].resource.ofType(MedicationDispense).extension[0]: Does not match slice 'prescription' 6.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).extension[0]: Bundle.entry[6].resource.ofType(MedicationDispense).extension[0]: Does not match slice 'pharmaceuticalAdvice' 7.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).extension[0]: Bundle.entry[6].resource.ofType(MedicationDispense).extension[0]: Does not match slice 'treatmentPlan' 8.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Does not match slice 'nonstructured' 9.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.dosageInstruction[0]: Dosage.text: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-nonstructured) 10.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.dosageInstruction[0]: Dosage.timing: max allowed = 0, but found 1 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-nonstructured) 11.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.dosageInstruction[0]: Dosage.route: max allowed = 0, but found 1 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-nonstructured) 12.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.dosageInstruction[0]: Dosage.doseAndRate: max allowed = 0, but found 1 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-nonstructured) 13.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Does not match slice 'structurednormal' 14.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.dosageInstruction[0].doseAndRate[0].dose.ofType(Quantity).code: The value provided ('732936001') is not in the value set http://fhir.ch/ig/ch-emed/ValueSet/UnitCode (http://fhir.ch/ig/ch-emed/ValueSet/UnitCode), and a code is required from this value set) (error message = Failed to expand ValueSet 'http://fhir.ch/ig/ch-emed/ValueSet/UnitCode' (in-memory). Could not validate code null#732936001) 15.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Does not match slice 'structuredsplit' 16.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.dosageInstruction[0]: Dosage.sequence: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-structured-split) 17.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.ofType(MedicationDispense).dosageInstruction[0]: Bundle.entry[6].resource.dosageInstruction[0].doseAndRate[0].dose.ofType(Quantity).code: The value provided ('732936001') is not in the value set http://fhir.ch/ig/ch-emed/ValueSet/UnitCode (http://fhir.ch/ig/ch-emed/ValueSet/UnitCode), and a code is required from this value set) (error message = Failed to expand ValueSet 'http://fhir.ch/ig/ch-emed/ValueSet/UnitCode' (in-memory). Could not validate code null#732936001) 18.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).contained[0].ofType(MedicationDispense).amount.numerator.code: The value provided ('732936001') is not in the value set http://fhir.ch/ig/ch-emed/ValueSet/UnitCode (http://fhir.ch/ig/ch-emed/ValueSet/UnitCode), and a code is required from this value set) (error message = Failed to expand ValueSet 'http://fhir.ch/ig/ch-emed/ValueSet/UnitCode' (in-memory). Could not validate code null#732936001) 19.) Bundle.entry[0]: Bundle.entry[6].resource.ofType(MedicationDispense).contained[0].ofType(MedicationDispense).ingredient[0].strength.denominator.code: The value provided ('732936001') is not in the value set http://fhir.ch/ig/ch-emed/ValueSet/UnitCode (http://fhir.ch/ig/ch-emed/ValueSet/UnitCode), and a code is required from this value set) (error message = Failed to expand ValueSet 'http://fhir.ch/ig/ch-emed/ValueSet/UnitCode' (in-memory). Could not validate code null#732936001)
