### ISSUE TITLE
Remove language requirements of titles (annatina foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#70]
ch.fhir.ig.ch-emed#1.0.0 /

goes back to this discussion during PAT'21: "the problem is not in the validation or spec, CH-EMED requires specific text titles in the corresponding language, see the requirement in the constraints section, e.g. fr the medication card it is here: http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-composition-medicationcard.html#constraints . So you cannot just switch the language code but you need to also switch the 3 titles and then the validation goes through .... the error message however could be improved " -> i think this requirement is not helpful, should be removed

annatina foppa, eHealth Suisse

**Comment by pjolo** [comment]
Rückmeldung Quentin Ligier:
Theoretisch ja, einige Titel (Dokument und Item) sind für die üblichen Sprachen (Englisch, Deutsch, Französisch, Italienisch) festgelegt, aber die Übersetzungen in die anderen Sprachen sind frei wählbar (man kann also einfach die Sprache des Dokuments ändern und irgendetwas als Titel setzen).
Ich sehe nicht ganz den Sinn darin, den Titel frei wählbar zu lassen, daher nehme ich an, dass im Sinne der Spezifikation die Grundabsicht darin bestand, einen festen Titel zu haben, entweder in Deutsch, Französisch oder Italienisch, je nachdem, in welcher Region das CDA erstellt wurde.

**Comment by ziegm** [comment]
Finaler Entscheid:
So belassen wie es ist.

**Comment by ziegm** [comment]
@pjolo :  Please review and close the ticket.
