### ISSUE TITLE
stronger binding of time-values than "highly recommended"? Dosage (annatina foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#73]
ch.fhir.ig.ch-emed#1.0.0 /dosage.html

I saw some examples during Projectathon of different timing values. since the recommendation is not respected we should think of a stronger requirement

annatina foppa, eHealth Suisse

**Comment by ziegm** [comment]
* Explizit markiert als Dosierung 1-1-1-1, trotzdem Möglichkeit um andere Schemas anzuwenden. Abweichung zu üblichem Handling (fixes Schema für CH).
* **1. Schritt: Warning**
* Weiterer Schritt wenn mehrere Dosierungstypen kommen: Markieren welcher Typ

**Comment by ziegm** [comment]
@pjolo 
Please review the change: 
* Constraint **ch-emed-event-timing** in the [CH EMED Dosage Structured Profile](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue73/StructureDefinition-ch-emed-dosage-structured.html)
* [Example for MedicationStatment with NOT recommended timing codes](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue73/MedicationStatement-NotRecommendedTimingCodes.json.html) (CM, CV)
   * [Warning that non-recommended codes are used](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue73/qa.html#_scratch_ig-build-temp-6MS2ES_repo_input_examples_medicationstatement_NotRecommendedTimingCodes)

If it is okay, please merge this [PR](https://github.com/ehealthsuisse/ch-emed/pull/81) and close the issue.
