### ISSUE TITLE
Why are patient and author not must-support flagged? -- CH EMED Medication Card Composition Profile (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-emed#75]
ch.fhir.ig.ch-emed#1.0.0 /StructureDefinition-ch-emed-composition-medicationcard.html

In my opinion, they should be, since they belong to the minimal data set of IPAG

Annatina Foppa, eHealth Suisse

**Comment by ziegm** [comment]
If it is okay, please merge the [PR](https://github.com/ehealthsuisse/ch-emed/pull/79) and close the issue.

**Comment by ziegm** [comment]
discussed in telco, okay
