### ISSUE TITLE
Practitioner must be provided in Composition.author

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-emed#80]
For the medication exchange formats the Author ('Behandelnder') is required for all the exchange formats.
(This is also required in the base [CDA-CH templates](https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.9.23&effectiveDate=2019-09-12T13:48:28&language=en-US)).

1. The FHIR CH-EMED specification needs a reference to Practitioner or PractitionerRole. If PractitionerRole is used the the Practitioner within is not enforced (cardinality zero). We need to either remove the PractitionerRole as an author or require the practitionerRole that it contains a Practitioner.

2. composition author targets: Device | CH Core Patient Profile EPR | RelatedPerson | CH Core Organization Profile EPR should be removed from all exchange formats (except for the Medication List where Device might be also added if it is used in a CMPD envirornement).

3. Should we enforce Practitioner (Behandelnder) with  Name Vorname GLN-Nr. Adresse PLZ Ort

**Comment by ziegm** [comment]
Anmerkung zu Punkt 2:
Sollte Device wirklich entfernt werden? Bsp. von PAT '21 zu Composition.author
```json
"author": [
  {
    "reference": "Device/Converter-CHMED-EmedFhir"
  },
  {
    "reference": "Practitioner/a201fd9a-b852-47d2-bda4-876b16ac133d"
  }
],
```

**Comment by ziegm** [comment]
1./3.  Composition.author
   - PractitionerRole EMED von EPR abgeleitet -> Practititioner EMED 1..
   - Practitioner EMED abgeleitet von Practitioner EPR mit address 1..
2. target profiles von author so belassen

**Comment by ziegm** [comment]
@pjolo
Please review the change. If it is okay, please merge this [PR](https://github.com/ehealthsuisse/ch-emed/pull/83) and close the issue.

* [CH EMED Medication Card Composition Profile](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue80/StructureDefinition-ch-emed-composition-medicationcard.html)
* [CH EMED PractitionerRole Profile](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue80/StructureDefinition-ch-emed-practitionerrole.html)
* [CH EMED Practitioner Profile](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue80/StructureDefinition-ch-emed-practitioner.html)
* updated example for Practitioner (add address): [Familien Hausarzt](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/issue80/Practitioner-FamilienHausarzt.html)
