### ISSUE TITLE
Case sensitivity in code systems

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-emed#84]
New validation issues:
* [codesystem\v3-TimingEvent.xml](https://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/master/qa.html#_scratch_ig-build-temp-PPM1S4_repo_input_resources_codesystem_v3-TimingEvent): 
**error:** CodeSystems SHOULD NOT have a stated value for the caseSensitive element when they are a supplement
   * Typo in the error, should be "CodeSystems SHOULD NOT have a stated value for the hierarchyMeaning element when they are a supplement" (see the discussion on [zulip](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/case.20sensitivity.20in.20a.20code.20system.20.28supplement.29)).
* [codesystem/ihe-pharmaceuticaladvicestatuslist.xml](https://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/master/qa.html#_scratch_ig-build-temp-PPM1S4_repo_input_resources_codesystem_ihe-pharmaceuticaladvicestatuslist):
**information:** CodeSystems SHOULD have a stated value for the caseSensitive element so that users know the status and meaning of the code system clearly
* [codesystem/edqm-standardterms.xml](https://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/master/qa.html#_scratch_ig-build-temp-PPM1S4_repo_input_resources_codesystem_edqm-standardterms):
**information:** CodeSystems SHOULD have a stated value for the caseSensitive element so that users know the status and meaning of the code system clearly

**Comment by ziegm** [comment]
For the 2 informations, we would have to add the element `<caseSensitive value="true"/>`.
For the error, see the discussion in [zulip](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/case.20sensitivity.20in.20a.20code.20system.20.28supplement.29).

**Comment by oliveregger** [comment]
need to clarify if the two codesystems are case-sensitive or not

**Comment by qligier** [comment]
All codes should be case-sensitive within CDA-CH-EMED and I will treat them as such. There are issues with some code systems (e.g. UCUM) and the Schematron does a case-sensitive comparison with value sets codes.

**Comment by ziegm** [comment]
TBD: Für beide Code Systeme recherchieren und definieren.

**Comment by ziegm** [comment]
@oliveregger : Anpassung bei der Generierung noch notwendig
